
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/careercoachbooking
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jooq:
    sql-dialect: mysql

logging:
  level:
    org.jooq: DEBUG
    org.example.careercoachbookingsystem: DEBUG